spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=transaction_schema
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
user.service.url=http://user-mgmt:8080/api/v1
server.servlet.context-path=/api/v1

# transaction-service application.properties

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

server.error.include-message=always
server.error.include-binding-errors=always

